#!/bin/sh

if [ -z "$USER" ]; then
    USER=$(id -un)
fi

echo >&2 "====================================================================="
echo >&2 " Setting up codespaces environment"
echo >&2 ""
echo >&2 " USER        $USER"
echo >&2 " HOME        $HOME"
echo >&2 "====================================================================="

# Make passwordless sudo work
export SUDO_ASKPASS=/bin/true

mv bashrc $HOME/.bashrc
mkdir -p $HOME/.config
mv nvim $HOME/.config/nvim
mv helix $HOME/.config/helix
mv tmux.conf $HOME/.tmux.conf
mv git_prompt.sh ~/.git_prompt.sh
mv gitconfig $HOME/.gitconfig

sudo add-apt-repository ppa:maveonair/helix-editor
sudo apt-get update -y
sudo apt-get install -y helix tmux
