#!/bin/sh

if [ -z "$USER" ]; then
    USER=$(id -un)
fi

echo >&2 "====================================================================="
echo >&2 " Setting up codespaces environment"
echo >&2 ""
echo >&2 " USER        $USER"
echo >&2 " HOME        $HOME"
echo >&2 "====================================================================="

# Make passwordless sudo work
export SUDO_ASKPASS=/bin/true

mv bashrc $HOME/.bashrc
mkdir -p $HOME/.config
mv nvim $HOME/.config/nvim
mv helix $HOME/.config/helix
mv tmux.conf $HOME/.tmux.conf
mv git_prompt.sh ~/.git_prompt.sh
mv gitconfig $HOME/.gitconfig

# sudo add-apt-repository ppa:maveonair/helix-editor
# sudo apt-get update -y
# sudo apt-get install -y helix tmux

HELIXVERSION=23.10

echo "Activating feature 'helix-editor'"
echo "Installing version ${HELIXVERSION}"

apt-get -y update
apt-get -y upgrade --no-install-recommends
DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends curl ca-certificates xz-utils
apt-get -y autoremove
apt-get -y clean

cd /tmp
curl -fLO https://github.com/helix-editor/helix/releases/download/${HELIXVERSION}/helix-${HELIXVERSION}-x86_64-linux.tar.xz
tar xJf helix-${HELIXVERSION}-x86_64-linux.tar.xz
rm -f helix-${HELIXVERSION}-x86_64-linux.tar.xz
install -D helix-${HELIXVERSION}-x86_64-linux/hx /usr/local/bin/hx

mv helix-${HELIXVERSION}-x86_64-linux/runtime $HOME/.config/helix
rm -rf helix-${HELIXVERSION}-x86_64-linux

echo "Helix ${HELIXVERSION} installed as /usr/local/bin/hx"
